version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/my-app1
hooks:
  BeforeInstall:
    - location: scripts/codedeploy_before_install.sh
      timeout: 600
      runas: ubuntu
  AfterInstall:
    - location: scripts/codedeploy_after_install.sh
      timeout: 1000
      runas: ubuntu
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file