version: 0.1
os: linux
files:
  - source: /
    destination: /var/www/html  # Specify the destination directory on the EC2 instance

hooks:
  BeforeInstall:
    - location: /bin/bash  # Path to a script to clean up previous deployment artifacts
      runas: root
      commands:
        - sudo apt-get install nodejs-legacy -y
        - sudo apt-get install npm  -y
        - sudo npm install pm2 -g
        - sudo rm -rf /var/www/html

  AfterInstall:
    - location: /bin/bash
      runas: root
      timeout: 180
      timeoutSignal: SIGTERM
      commands:
        - npm install --production

  ApplicationStart:
    - location: /bin/bash
      runas: ubuntu  # User to run the script as
      timeout: 180
      timeoutSignal: SIGTERM
      commands:
        - npm start

  ValidateService:
    - location: /bin/bash
      runas: ubuntu  # User to run the script as
      timeout: 180
      timeoutSignal: SIGTERM
      commands:
        - # Add additional validation or test commands here
